### ISSUE TITLE
I'm making a simplified Chinese package. How can I submit it?

### ISSUE THREAD

**Issue by shenyx110** [stevexg/AgeOfWeapons#11]
我正在制作简体中文汉化包 请问如何提交

I'm making a simplified Chinese package. How can I submit it?

**Comment by shenyx110** [comment]
[AOW.zip](https://github.com/stevexg/AgeOfWeapons/files/11504032/AOW.zip)
Simplified Chinese language package

**Comment by shenyx110** [comment]
Key bug fixes
[AOW.zip](https://github.com/stevexg/AgeOfWeapons/files/11504606/AOW.zip)

**Comment by shenyx110** [comment]
Some better translate 
 "item.ageofweapons.buster_sword": "破坏者之剑",
    "item.ageofweapons.elucidator": "启示者",
    "item.ageofweapons.excalibur": "石中圣剑",
    "item.ageofweapons.master_sword": "宗师之力",
    "item.ageofweapons.nightmare_scythe": "梦魇之镰",
    "item.ageofweapons.sword_of_kings": "王者之剑",
    "item.ageofweapons.titan_sword": "泰坦巨剑",
    "item.ageofweapons.leviathan_axe": "利维坦之斧",

**Comment by XxRexRaptorxX** [comment]
Thanks for your translation!

If you have discord you will get the translator rank on my server as a reward! > https://discord.com/invite/ycRJJk8EXV
