### ISSUE TITLE
Oversized textures

### ISSUE THREAD

**Issue by LemADEC** [stevexg/AgeOfWeapons#7]
As of Age of Weapons 1.12.2  (v.0.13.5), textures for stone age are largely oversized to 128x128 when 16x16 would be enough.
Please reduce those textures to a more reasonable size.

**Comment by XxRexRaptorxX** [comment]
Which textures exactly do you mean?

**Comment by LemADEC** [comment]
items/epic/legendary_sword
blocks/withered_iron_block
items/epic/master_pickaxe
items/basic/withered_iron_ingots
etc.

Looks like it's the withered iron ones, not the stone age ones, by bad

**Comment by XxRexRaptorxX** [comment]
Thats a 'feature', this are special items that has ingame a cool 'shader'-thing in the textures

**Comment by XxRexRaptorxX** [comment]
A few other bigger weapons have this size too, because they need it to make a better looking texture for it

**Comment by LemADEC** [comment]
This prevent low end computer to play the mod. Consider adding an actual shader like the enchantment glitter effect or some colors if you want to make it special

**Comment by XxRexRaptorxX** [comment]
~10   128×128 textures don't overload your pc ;)    
If anyone still have a problem with it, create a resource pack :)

**Comment by LemADEC** [comment]
This what those oversized textures look compared to vanilla:
![image](https://user-images.githubusercontent.com/4776032/41006945-d98d8c86-6923-11e8-9a8b-9db07e4aace9.png)

In math terms, each 128x128 texture is as much space as 64 vanilla ones.
The epic sword is 256x256, which is 4 times more.
All in all, just those ~15 items are taking the same of 1024 reasonably sized textures.

**Comment by XxRexRaptorxX** [comment]
Okay, maybe i reduce the size to 64x64 or 128x128
